version: "2"
services:
  proxy:
    image: quay.io/spesnova/nginx-example:latest
    container_name: proxy
    ports:
      - 80:8080
    volumes_from:
      - web
    depends_on:
      - web
    stop_signal: SIGQUIT
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
  web:
    build: .
    command: [bundle, exec, puma, -C, config/puma.rb]
    container_name: web
    volumes:
      - /app/tmp
      - /app/public
    depends_on:
      - db
    links:
      - db
    env_file: .env
    stop_signal: SIGQUIT
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=postgres://hello:world@db:5432/example
      - SECRET_KEY_BASE=61f9fb4243fcf0a8caa6a141f5c03a66eb0be9e1568037fd0201deb31aa392644f9b70e7346d47ccda90bbfc2e8c261c674cc9133c10ab45e73caa02e6e2a2c0
  db:
    image: postgres:9.5.1
    container_name: db
    stop_signal: SIGTERM
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=world
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
  test:
    image: quay.io/spesnova/infrataster:latest
    volumes:
      - ./test/container:/test/spec
    depends_on:
      - proxy
    network_mode: "service:proxy"

  fluentd:
    image: fluent/fluentd:latest
    volumes:
      - /home/docker/log:/fluentd/log
    ports:
      - 24224:24224

