apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: db-create
spec:
  selector:
    matchLabels:
      name: db-create
      app: example
  template:
    metadata:
      name: db-create
      labels:
        name: db-create
        app: example
    spec:
      restartPolicy: Never
      containers:
      - name: db-create
        image: quay.io/spesnova/rails-example:latest
        command: ["bundle", "exec", "rake", "db:create"]
        env:
        - name: "RACK_ENV"
          value: "production"
        - name: "RAILS_ENV"
          value: "production"
        - name: "DATABASE_URL"
          value: "postgres://hello:world@db:5432/example"
        - name: "SECRET_KEY_BASE"
          value: "61f9fb4243fcf0a8caa6a141f5c03a66eb0be9e1568037fd0201deb31aa392644f9b70e7346d47ccda90bbfc2e8c261c674cc9133c10ab45e73caa02e6e2a2c0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
