apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: example
    status: active
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: web
    app: example
    status: active
